name: CI Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rspec:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby_version: [2.6, 2.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - name: Install dependencies
      run: |
        gem install bundler -v 2.1.4 --no-document
        bundle install --jobs 4 --retry 3

    - name: Build and test with Rake
      run: |
        bundle exec rspec
