name: CI Matrix Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rspec:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby_version: [2.5, 2.6]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - name: Install sqlite3
      run: |
        sudo apt-get install libsqlite3-dev

    - name: Install dependencies
      run: |
        gem install bundler -v 2.1.4 --no-document
        bundle install --jobs 4 --retry 3

    - name: Build and test with Rake
      run: |
        bundle exec rspec

  build:
    name: Publish Gem
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: 2.7.x

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}

